### ISSUE TITLE
Trained model?

### ISSUE THREAD

**Issue by branimir29** [infrontofme/UWGAN_UIE#1]
Hello, I am interested in trying your method on my own underwater images.
However, downloading full NYU image sets requires for V1 90GB (Raw images) and for v2 it's 428GB for V2. I simply don't have enough space or time to wait to download all this.
So, I was wondering if you could upload pre-trained UWGAN/U-Net models instead that one could simply download and try on real life underwater images? It would be a great help.

**Comment by 02250119** [comment]
I met the same problem

**Comment by infrontofme** [comment]
@branimir29 @02250119 
Thank you very much for your interest in our project.

Our computing server crashed two weeks ago due to some unexpected reasons, resulting in data loss on the server, including pre-trained models for our project. We are trying to recover the data or retrain our model, but this may take several weeks. Please be patient.

We used only part of the data in the NYU Depth Datasets to train UWGAN, and this part of the data was uploaded to _[Baidu Cloud Link](https://pan.baidu.com/s/1msG0UjvRCT391HyiWuFiVQ)_. With these RGB-D data and underwater RGB images, you should be able to use UWGAN to synthesize underwater-style images, and then you can train U-net with image pairs.

You are welcome to follow our project at any time, if there is any update, we will push it on Github.

**Comment by branimir29** [comment]
Thanks for quick reply @infrontofme . There is no way for me to access Baidu Cloud, any chance you could forward me that package from Baidu via WeTransfer, GDrive, Dropbox? 
It would be a great help.

**Comment by infrontofme** [comment]
@branimir29 
We have uploaded datasets to Google Drive, you can find underwater images here [WaterImages](https://drive.google.com/open?id=1S2T5gZbdNe9KvVqGf-Neul3clRrpymPo), and you can find RGB-D images here [NYU](https://drive.google.com/open?id=1q1FEcuhMPtqjJgaPSriL8EiBYA-mNGZv).
If you have any questions about our project, please contact us.

**Comment by 02250119** [comment]
Thank you for your reply.It will help me.

**Comment by branimir29** [comment]
That's really nice of you, thx. I downloaded Water images, but NYU require your permission to access. I sent access request from my gmail address you'll see.

**Comment by Jinksi** [comment]
@infrontofme did you recover the trained model and make it publicly available?

**Comment by infrontofme** [comment]
the trained model has been recovered, the pre-trained model and datasets will be made publicly available soon.

**Comment by priyank200** [comment]
Hello, @infrontofme, can you please provide me the requirement.txt file? I want to run the code with a small dataset.
